image: registry.gitlab.com/depili/clock-8001:latest

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive


cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build
  - deploy

before_script:
  - mkdir -p /go/src/gitlab.com/Depili /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/Depili/clock-8001
  - ln -s /go/src/gitlab.com/Depili /go/src/_/builds/clock-8001
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  variables:
    CC: clang-7
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

# code_coverage_report:
#  stage: test
#  script:
#    - make coverhtml
#  only:
#  - master

lint_code:
  stage: test
  script:
    - make lint

build:
  image: registry.gitlab.com/depili/clock-8001-build:master
  stage: build
  script:
    - make build
  artifacts:
     paths:
     - matrix-clock
     - sdl-clock
     - clock-8001

deploy_latest:
    stage: deploy
    environment: Testing
    before_script: {}
    script:
        - apt-get update -qq && apt-get install -y -qq sshpass
        - ls
        - sshpass -V
        - export SSHPASS=$USER_PASS
        - export TS=$(date +%Y-%m-%d-%H%M%S)
        - sshpass -e scp -o stricthostkeychecking=no sdl-clock clock8001@kissa.depili.fi:/var/www/html/clock-8001/testing/sdl-clock-$TS
        - sshpass -e scp -o stricthostkeychecking=no matrix-clock clock8001@kissa.depili.fi:/var/www/html/clock-8001/testing/matrix-clock-$TS
    only:
        - master

deploy_release:
    stage: deploy
    environment: Stable
    before_script: {}
    script:
        - apt-get update -qq && apt-get install -y -qq sshpass
        - ls
        - sshpass -V
        - export SSHPASS=$USER_PASS
        - export TS=$(date +%Y-%m-%d-%H%M%S)
        - sshpass -e scp -o stricthostkeychecking=no sdl-clock clock8001@kissa.depili.fi:/var/www/html/clock-8001/releases/sdl-clock-$CI_COMMIT_TAG
        - sshpass -e scp -o stricthostkeychecking=no matrix-clock clock8001@kissa.depili.fi:/var/www/html/clock-8001/releases/matrix-clock-$CI_COMMIT_TAG
        - curl -X POST -F token=$BR_TOKEN -F "ref=master" -F "variables[CLOCK_TAG]=$CI_COMMIT_TAG" https://gitlab.com/api/v4/projects/10763408/trigger/pipeline
    artifacts:
      paths:
        - matrix-clock
        - sdl-clock
        - clock-8001
      name: "clock-8001-release-$CI_COMMIT_TAG"
    only:
        - tags
